version: '3'
services:
  proxy:
    image: drill4j/devtools-proxy:0.0.4
    build: ./
    ports:
      - '8093:8080'
    environment:
      DEBUG: 'drill:*'
      DEBUG_COLORS: 'true'
      FORCE_COLOR: '3'
      DEBUG_LOG_LEVEL: '2'
